### ISSUE TITLE
MySQL Problem

### ISSUE THREAD

**Issue by SlimaKCoder** [games647/LagMonitor#10]
`com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'free_space' at row 1`

Full: http://pastebin.com/4nBbwEFB

**Comment by games647** [comment]
What's the output of /env ?

**Comment by SlimaKCoder** [comment]
Minecraft: /env
```
[08:48:30 INFO]: OS Name: Linux
[08:48:30 INFO]: OS Version: 4.4.13-2-pve
[08:48:30 INFO]: OS Arch: amd64
[08:48:30 INFO]: Cores: 2
[08:48:30 INFO]: CPU: null
[08:48:30 INFO]: Load Average: 0.33
[08:48:30 INFO]: System Usage: 6.907 %
[08:48:30 INFO]: Process Usage: 4.4314 %
[08:48:30 INFO]: Total Swap: 0 B
[08:48:30 INFO]: Free Swap: 0 B
[08:48:30 INFO]: Total OS RAM: 3.46 GB
[08:48:30 INFO]: Free OS RAM: 2.00 GB
[08:48:30 INFO]: Disk Size: 21.00 GB
[08:48:30 INFO]: Free Space: 19.37 GB
```

Minecraft: /ver 
```
[08:48:37 INFO]: This server is running CraftBukkit version git-Spigot-90f61bc-83a9dbd (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
[08:48:37 INFO]: Checking version, please wait...
[08:48:38 INFO]: You are running the latest version
```

MySQL
```
root@db:/$ mysql --version
mysql  Ver 15.1 Distrib 10.1.16-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```
Java
```
minecraft@s1:~/server$ java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

**Comment by SlimaKCoder** [comment]
But anyway `Data truncation: Out of range value for column 'free_space' at row 1` suggest to be a SQL problem with datatypes and their sizes.

**Comment by games647** [comment]
yeah I know. I just needed this: 
[08:48:30 INFO]: Disk Size: 21.00 GB
[08:48:30 INFO]: Free Space: 19.37 GB

**Comment by games647** [comment]
I think it's an integer overflow, because of the minus.

**Comment by games647** [comment]
Could you try it out?

**Comment by SlimaKCoder** [comment]
Ok, but i need compiled .jar file :)

**Comment by games647** [comment]
https://github.com/games647/LagMonitor/releases/tag/mysql-native

**Comment by SlimaKCoder** [comment]
Saved as LagMonitor-v.1.7.1.jar and seems to work, thank you!

**Comment by SlimaKCoder** [comment]
```
[14:02:33 ERROR]: [LagMonitor] Error saving native stats to database
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'mc_write' at row 1
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3868) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
        at com.github.games647.lagmonitor.storage.Storage.saveNative(Storage.java:254) [LagMonitor-v.1.7.1.jar:?]
        at com.github.games647.lagmonitor.storage.NativeSaveTask.run(NativeSaveTask.java:93) [LagMonitor-v.1.7.1.jar:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[14:02:33 ERROR]: [LagMonitor] Using this data [0, -1, 18472, 92.2217, 0, 0, 0, 0]

```

**Comment by games647** [comment]
Do you activated traffic reader?

**Comment by SlimaKCoder** [comment]
Yep
`traffic-counter: true`
