### ISSUE TITLE
Spigot 1.17 support

### ISSUE THREAD

**Issue by Dymeth** [games647/LagMonitor#128]
The mappings have changed in version 1.17 (Spigot). This results in an exception when starting the plugin: 

```
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
<...>
Caused by: java.lang.IllegalArgumentException: Cannot find net.minecraft.server.v1_17_R1.EntityPlayer
at LagMonitor.jar//com.github.games647.lagmonitor.traffic.Reflection.getCanonicalClass(Reflection.java:362)
at LagMonitor.jar//com.github.games647.lagmonitor.traffic.Reflection.getMinecraftClass(Reflection.java:339)
at LagMonitor.jar//com.github.games647.lagmonitor.tasks.PingManager.<clinit>(PingManager.java:37)
```

**Comment by games647** [comment]
Which version of the plugin do you run? If you are not using a dev build, could you try that?

**Comment by Dymeth** [comment]
> Which version of the plugin do you run? If you are not using a dev build, could you try that?
Tested on Paper-281 (MC: 1.17.1):

The problem occurs with the latest release (v1.17) on SpigotMC.
But with the latest dev build (v1.17.2-SNAPSHOT-5c40f7f), the plugin starts correctly
