### ISSUE TITLE
[Suggestion] Web page to show Monitor

### ISSUE THREAD

**Issue by Eufranio** [games647/LagMonitor#13]
Would be usefull if you make /monitor feature creates a web page instead a bigger and super-detailed message, similar to what WarmRoast does (it is abandoned and is not working here)

How would work?

After the /monitor command, a link would be displayed in the chat, going to a web page similar to WarmRoast page, more undestandable.

**Comment by games647** [comment]
Maybe I could make use of http://paste.enginehub.org/ . (currently not available for unknown reasons)

**Comment by Eufranio** [comment]
Printing all the tasks, like the chat?
It's really confusing :/

**Comment by games647** [comment]
http://paste.enginehub.org/ works like clickable stack tree.

**Comment by Eufranio** [comment]
Oh yeah then it would be cool xD

**Comment by games647** [comment]
I'll wait until the website comes back. It's seems like it's currently misconfigured.

**Comment by games647** [comment]
It's back online. So what do you think about it?

Here is an example: http://paste.enginehub.org/fdUcqC.profile

**Comment by Eufranio** [comment]
Perfect! :smile:

**Comment by Eufranio** [comment]
Is there a jenkins?

**Comment by games647** [comment]
Yes. http://ci.xephi.fr/job/LagMonitor/changes

But you could also use the latest version from Spigot.

**Comment by Eufranio** [comment]
```
>monitor paste
[20:51:29 WARN]: Exception in thread "Craft Scheduler Thread - 9"
[20:51:29 WARN]: org.apache.commons.lang.UnhandledException: Plugin LagMonitor v1.9 generated an exception while executing task 75
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: guava10/com/google/common/io/Closer
        at com.github.games647.lagmonitor.tasks.MonitorTask.paste(MonitorTask.java:86)
        at com.github.games647.lagmonitor.commands.MonitorCommand$1.run(MonitorCommand.java:136)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by games647** [comment]
LagMonitor doesn't work below 1.8

**Comment by Eufranio** [comment]
f*ck
:/
