### ISSUE TITLE
Blocked MySQL Socket

### ISSUE THREAD

**Issue by SlimaKCoder** [games647/LagMonitor#15]
Maybe LagMonitor needs to use MySQL not in main thread?
```
[10:12:51] [Server thread/WARN]: [LagMonitor] Server is performing a blocking socket connection socket://db.xxxxx.com:3306 on the main thread
[10:12:51] [Server thread/WARN]: [LagMonitor] 
java.lang.Throwable
	at com.github.games647.lagmonitor.listeners.BlockingConnectionSelector.select(BlockingConnectionSelector.java:31) [LagMonitor-v.1.9.jar:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384) [?:1.8.0_101]
	at java.net.Socket.connect(Socket.java:589) [?:1.8.0_101]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:214) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2252) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2285) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2084) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_101]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_101]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_101]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_101]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) [?:1.8.0_101]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) [?:1.8.0_101]
	at com.github.games647.lagmonitor.storage.Storage.getConnection(Storage.java:284) [LagMonitor-v.1.9.jar:?]
	at com.github.games647.lagmonitor.storage.Storage.createTables(Storage.java:53) [LagMonitor-v.1.9.jar:?]
	at com.github.games647.lagmonitor.LagMonitor.onEnable(LagMonitor.java:140) [LagMonitor-v.1.9.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by games647** [comment]
Nice the plugin is also detecting my own mistakes.

**Comment by sgdc3** [comment]
xD

**Comment by SlimaKCoder** [comment]
Error still exists, but in runtime, not at start
```
[17:19:39] [Server thread/WARN]: [LagMonitor] Server is performing a blocking socket connection socket://ashooole.com:3306 on the main thread
[17:19:39] [Server thread/WARN]: [LagMonitor] 
java.lang.Throwable
	at com.github.games647.lagmonitor.listeners.BlockingConnectionSelector.select(BlockingConnectionSelector.java:31) [LagMonitor-v.1.9.1.jar:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384) [?:1.8.0_101]
	at java.net.Socket.connect(Socket.java:589) [?:1.8.0_101]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:214) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2252) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2285) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2084) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at sun.reflect.GeneratedConstructorAccessor56.newInstance(Unknown Source) [?:1.8.0_101]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_101]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_101]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) [?:1.8.0_101]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) [?:1.8.0_101]
	at net.sacredlabyrinth.phaed.simpleclans.storage.MySQLCore.initialize(MySQLCore.java:46) [SimpleClan-x7.jar:?]
	at net.sacredlabyrinth.phaed.simpleclans.storage.MySQLCore.getConnection(MySQLCore.java:68) [SimpleClan-x7.jar:?]
	at net.sacredlabyrinth.phaed.simpleclans.storage.MySQLCore.select(MySQLCore.java:117) [SimpleClan-x7.jar:?]
	at net.sacredlabyrinth.phaed.simpleclans.managers.StorageManager.retrieveClans(StorageManager.java:307) [SimpleClan-x7.jar:?]
	at net.sacredlabyrinth.phaed.simpleclans.managers.StorageManager.importFromDatabase(StorageManager.java:183) [SimpleClan-x7.jar:?]
	at net.sacredlabyrinth.phaed.simpleclans.commands.ReloadCommand.execute(ReloadCommand.java:37) [SimpleClan-x7.jar:?]
	at net.sacredlabyrinth.phaed.simpleclans.executors.ClanCommandExecutor.onCommand(ClanCommandExecutor.java:320) [SimpleClan-x7.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:438) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:401) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by games647** [comment]
It's not/bug. It's a feature. 

https://github.com/games647/LagMonitor/issues/14#issuecomment-246017087

>It shows you were the code is making this blocking connection. Http **(or in this case SQL)** requests should be performed async and not on the main thread. 

This could be a performance hit, that's why LagMonitor informs you about it. Otherwise it could be hard to find such cases.

**Comment by SlimaKCoder** [comment]
Ok, this one is good, simple short warning:
```
[17:19:39] [Server thread/WARN]: [LagMonitor] Server is performing a blocking socket connection socket://ashooole.com:3306 on the main thread
```
But this one is totally spam and everybody love such spamming features. I know, I know, it's very important crap, but please add way to log it into file instead of console or way to disable it.
```
[17:19:39] [Server thread/WARN]: [LagMonitor] 
java.lang.Throwable
    at com.github.games647.lagmonitor.listeners.BlockingConnectionSelector.select(BlockingConnectionSelector.java:31) [LagMonitor-v.1.9.1.jar:?]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384) [?:1.8.0_101]
    at java.net.Socket.connect(Socket.java:589) [?:1.8.0_101]
    at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:214) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2252) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2285) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2084) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at sun.reflect.GeneratedConstructorAccessor56.newInstance(Unknown Source) [?:1.8.0_101]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_101]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_101]
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at java.sql.DriverManager.getConnection(DriverManager.java:664) [?:1.8.0_101]
    at java.sql.DriverManager.getConnection(DriverManager.java:247) [?:1.8.0_101]
    at net.sacredlabyrinth.phaed.simpleclans.storage.MySQLCore.initialize(MySQLCore.java:46) [SimpleClan-x7.jar:?]
    at net.sacredlabyrinth.phaed.simpleclans.storage.MySQLCore.getConnection(MySQLCore.java:68) [SimpleClan-x7.jar:?]
    at net.sacredlabyrinth.phaed.simpleclans.storage.MySQLCore.select(MySQLCore.java:117) [SimpleClan-x7.jar:?]
    at net.sacredlabyrinth.phaed.simpleclans.managers.StorageManager.retrieveClans(StorageManager.java:307) [SimpleClan-x7.jar:?]
    at net.sacredlabyrinth.phaed.simpleclans.managers.StorageManager.importFromDatabase(StorageManager.java:183) [SimpleClan-x7.jar:?]
    at net.sacredlabyrinth.phaed.simpleclans.commands.ReloadCommand.execute(ReloadCommand.java:37) [SimpleClan-x7.jar:?]
    at net.sacredlabyrinth.phaed.simpleclans.executors.ClanCommandExecutor.onCommand(ClanCommandExecutor.java:320) [SimpleClan-x7.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:438) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:401) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by games647** [comment]
I think the stack trace is needed to find the source. What do you think about printing a warning only once per plug in? 

Moreover you can already disable it using blocked server configuration property.

**Comment by games647** [comment]
Or a configuration options  to hide the stack trace?

**Comment by SlimaKCoder** [comment]
Maybe both, once per plugin and option to disable it. First solution will be good for debugging without spam and second for production.
