### ISSUE TITLE
Could not load 'plugins/jna-5.5.0.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by Muacky** [games647/LagMonitor#150]
I tried with version 4.4.0 and it also didnt worked, im getting this on console, its a clean install of Spigot 1.12.2 with just this 2 plugins (LagMonitor and JNA)
[17:28:25 ERROR]: Could not load 'plugins/jna-5.5.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more

**Comment by games647** [comment]
JNA is not a plugin. It's a component that is used by plugins. LagMonitor for example needs in either the Lagmonitor folder or the newer Spigot libraries folder depending on which plugin version you run. `4.4.0` doesn't correspond to a release number, so I have no idea what you are running.
