### ISSUE TITLE
Reloading plugins with LagMonitor enabled does not seem to work

### ISSUE THREAD

**Issue by Maxetto** [games647/LagMonitor#23]
When I try to reload MobHunting with Plugman while LagMonitor is enabled on my server seems to break the correct reloading of the plugin:
```
10.01 14:18:32 [Server] ERROR Error occurred while enabling MobHunting v4.3.0 (Is it up to date?)
10.01 14:18:32 [Server] INFO java.lang.IncompatibleClassChangeError: Class one.lindegaard.MobHunting.storage.MySQLDataStore does not implement the requested interface one.lindegaard.MobHunting.storage.IDataStore
10.01 14:18:32 [Server] INFO at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:130) ~[?:?]
10.01 14:18:32 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:285) [PlugMan.jar:?]
10.01 14:18:32 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:238) [PlugMan.jar:?]
10.01 14:18:32 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:299) [PlugMan.jar:?]
10.01 14:18:32 [Server] INFO at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan.jar:?]
10.01 14:18:32 [Server] INFO at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104) [PlugMan.jar:?]
10.01 14:18:32 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
10.01 14:18:32 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

Again, this was reported before on the MobHunting issue tracker (https://github.com/Rocologo/MobHunting/issues/113) and redirected here by further testing.

**Comment by games647** [comment]
That seems weird, because LagMonitor doesn't rewrite classes or change class loading although it would be great feature for better method profiling. Do you placed a new version of MobHunting into the plugins folder?

**Comment by Maxetto** [comment]
Yes, I reloaded it due to an upgrade. Might be that the cause?

**Comment by games647** [comment]
Yes

**Comment by Maxetto** [comment]
Understood. So, can I close this?
