### ISSUE TITLE
MySQL Error on boot for recording data

### ISSUE THREAD

**Issue by FrozenBeard** [games647/LagMonitor#24]
Hey! First time using this plugin, database is all setup correctly as the tables have been populated and have some rows; but at boot, I get this error message, I assume its trying to put something into the database but failing.
`[18:12:01] [Server thread/WARN]: [LagMonitor] Plugin Stats is performing a blocking action to socket://192.168.0.21:3306 on the main thread This could be a performance hit. Report it to the plugin author
[18:12:01] [Server thread/WARN]: [LagMonitor] 
java.lang.Exception
	at com.github.games647.lagmonitor.listeners.BlockingConnectionSelector.select(BlockingConnectionSelector.java:40) ~[?:?]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_111]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_111]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:214) ~[patched_1.10.2.jar:git-Paper-916]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298) ~[patched_1.10.2.jar:git-Paper-916]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2252) ~[patched_1.10.2.jar:git-Paper-916]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2285) ~[patched_1.10.2.jar:git-Paper-916]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2084) ~[patched_1.10.2.jar:git-Paper-916]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) ~[patched_1.10.2.jar:git-Paper-916]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[patched_1.10.2.jar:git-Paper-916]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_111]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[patched_1.10.2.jar:git-Paper-916]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) ~[patched_1.10.2.jar:git-Paper-916]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) ~[patched_1.10.2.jar:git-Paper-916]
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:39) ~[?:?]
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256) ~[?:?]
	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2304) ~[?:?]
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2290) ~[?:?]
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2039) ~[?:?]
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533) ~[?:?]
	at nl.lolmewn.stats.mysql.MySQLStorage.generateTables(MySQLStorage.java:315) ~[?:?]
	at nl.lolmewn.stats.mysql.MySQLStorage.lambda$enable$77(MySQLStorage.java:447) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.10.2.jar:git-Paper-916]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.10.2.jar:git-Paper-916]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:798) [patched_1.10.2.jar:git-Paper-916]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-916]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-916]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]`

**Comment by games647** [comment]
>Plugin Stats is performing a blocking action to socket://192.168.0.21:3306 on the main thread This could be a performance hit. Report it to the plugin

**Comment by games647** [comment]
It's a feature of LagMonitor to detect that.

**Comment by FrozenBeard** [comment]
@games647 Literally 5 seconds before you posted I understood that its showing a stack trace showing exactly what is blocking, this is a really nifty feature! I just assumed it was the plugin being broken!
I will report this to the stats dev.
