### ISSUE TITLE
Torch Support

### ISSUE THREAD

**Issue by Yive** [games647/LagMonitor#28]
Just came across a server software called [Torch](https://github.com/TorchSpigot/Torch) & decided to test a bunch of plugins I find useful to server owners.

During my testing I found out that LagMonitor does not load when using Torch. Here's some information about the instance.

Torch Version: 1.11.2 (Git Commit: 246213d)
LagMonitor Version: 1.14
Error:
```[02:27:57] [Server thread/INFO]: [LagMonitor] Enabling LagMonitor v1.14
[02:27:57] [Server thread/ERROR]: Error occurred while enabling LagMonitor v1.14 (Is it up to date?)
java.lang.ExceptionInInitializerError
	at com.github.games647.lagmonitor.LagMonitor.onEnable(LagMonitor.java:90) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[Torchpowered-1.11.2.jar:git-Torch-"246213d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [Torchpowered-1.11.2.jar:git-Torch-"246213d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [Torchpowered-1.11.2.jar:git-Torch-"246213d"]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:380) [Torchpowered-1.11.2.jar:git-Torch-"246213d"]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:330) [Torchpowered-1.11.2.jar:git-Torch-"246213d"]
	at org.torch.server.TorchServer.initialAllWorldsChunk(TorchServer.java:1018) [Torchpowered-1.11.2.jar:git-Torch-"246213d"]
	at org.torch.server.TorchServer.loadDefaultWorlds(TorchServer.java:816) [Torchpowered-1.11.2.jar:git-Torch-"246213d"]
	at org.torch.server.TorchServer.init(TorchServer.java:2003) [Torchpowered-1.11.2.jar:git-Torch-"246213d"]
	at org.torch.server.TorchServer.run(TorchServer.java:495) [Torchpowered-1.11.2.jar:git-Torch-"246213d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: Cannot find field with type class net.minecraft.server.v1_11_R1.MinecraftServer
	at com.github.games647.lagmonitor.traffic.Reflection.getField(Reflection.java:182) ~[?:?]
	at com.github.games647.lagmonitor.traffic.Reflection.getField(Reflection.java:179) ~[?:?]
	at com.github.games647.lagmonitor.traffic.Reflection.getField(Reflection.java:125) ~[?:?]
	at com.github.games647.lagmonitor.traffic.Reflection.getField(Reflection.java:137) ~[?:?]
	at com.github.games647.lagmonitor.traffic.TinyProtocol.<clinit>(TinyProtocol.java:32) ~[?:?]
	... 11 more
[02:27:57] [Server thread/INFO]: [LagMonitor] Disabling LagMonitor v1.14
```

**Comment by sgdc3** [comment]
Torch breaks everything, you should ask to paper's dev.
