### ISSUE TITLE
BatchUpdateException if i join the server immediately after the startup

### ISSUE THREAD

**Issue by sgdc3** [games647/LagMonitor#32]
```
[23:43:55 ERROR]: [LagMonitor] Error saving player data to database
java.sql.BatchUpdateException: Data truncation: Out of range value for column 'ping' at row 1
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.12.1.jar:git-Paper-1178]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.12.1.jar:git-Paper-1178]
        at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1162) ~[patched_1.12.1.jar:git-Paper-1178]
        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1778) ~[patched_1.12.1.jar:git-Paper-1178]
        at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1262) ~[patched_1.12.1.jar:git-Paper-1178]
        at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[patched_1.12.1.jar:git-Paper-1178]
        at com.github.games647.lagmonitor.storage.Storage.savePlayers(Storage.java:217) [LagMonitor.jar:?]
        at com.github.games647.lagmonitor.storage.MonitorSaveTask.run(MonitorSaveTask.java:55) [LagMonitor.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.1.jar:git-Paper-1178]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.1.jar:git-Paper-1178]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.1.jar:git-Paper-1178]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'ping' at row 1
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971) ~[patched_1.12.1.jar:git-Paper-1178]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[patched_1.12.1.jar:git-Paper-1178]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[patched_1.12.1.jar:git-Paper-1178]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[patched_1.12.1.jar:git-Paper-1178]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2494) ~[patched_1.12.1.jar:git-Paper-1178]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[patched_1.12.1.jar:git-Paper-1178]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079) ~[patched_1.12.1.jar:git-Paper-1178]
        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1756) ~[patched_1.12.1.jar:git-Paper-1178]
        ... 10 more

```

**Comment by sgdc3** [comment]
Only happens with the first player that joins the server
