### ISSUE TITLE
Data truncation due to OS ram

### ISSUE THREAD

**Issue by sgdc3** [games647/LagMonitor#33]
This happens on systems with more than 64gb of ram

```
[22:27:15 ERROR]: [LagMonitor] Error saving monitor data to database
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'os_free_ram' at row 1
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971) ~[patched_1.12.1.jar:git-Paper-1197]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[patched_1.12.1.jar:git-Paper-1197]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[patched_1.12.1.jar:git-Paper-1197]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[patched_1.12.1.jar:git-Paper-1197]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2494) ~[patched_1.12.1.jar:git-Paper-1197]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[patched_1.12.1.jar:git-Paper-1197]
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197) ~[patched_1.12.1.jar:git-Paper-1197]
        at com.github.games647.lagmonitor.storage.Storage.saveMonitor(Storage.java:129) [LagMonitor.jar:?]
        at com.github.games647.lagmonitor.storage.MonitorSaveTask.onMonitorSave(MonitorSaveTask.java:148) [LagMonitor.jar:?]
        at com.github.games647.lagmonitor.storage.MonitorSaveTask.run(MonitorSaveTask.java:42) [LagMonitor.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.1.jar:git-Paper-1197]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.1.jar:git-Paper-1197]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.1.jar:git-Paper-1197]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by games647** [comment]
I think just the formula was incorrect, because 64 * 1024 fits perfectly into a unsigned small int.

**Comment by sgdc3** [comment]
My server has 128gb of ram xD

**Comment by sgdc3** [comment]
You should use a mediumint

**Comment by sgdc3** [comment]
i fixed the issue by altering the column type

**Comment by games647** [comment]
But I should change it nevertheless, so I reopened it for me as a reminder.
