### ISSUE TITLE
Console Warning at Start

### ISSUE THREAD

**Issue by tobimori** [games647/LagMonitor#34]
`[15:03:36 WARN]: [LagMonitor] Plugin skUtilities is performing a blocking action on the main thread. This could be a performance hit Socket: https://raw.githubusercontent.com/tim740/skUtilities/master/latest.ver. Such actions should be handled async from the main thread. Report it to the plugin author
[15:03:36 WARN]: [LagMonitor] The following exception is not an error. It's a hint for the plugin developer to find the source of the threading action. LagMonitor doesn't prevent this action. It just warns you
java.lang.IllegalAccessException: null
        at com.github.games647.lagmonitor.threading.BlockingActionManager.logCurrentStack(BlockingActionManager.java:55) ~[?:?]
        at com.github.games647.lagmonitor.threading.BlockingActionManager.checkBlockingAction(BlockingActionManager.java:42) ~[?:?]
        at com.github.games647.lagmonitor.listeners.BlockingConnectionSelector.select(BlockingConnectionSelector.java:27) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1132) ~[?:1.8.0_131]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) ~[?:1.8.0_131]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:1.8.0_131]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546) ~[?:1.8.0_131]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[?:1.8.0_131]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_131]
        at java.net.URL.openStream(URL.java:1045) ~[?:1.8.0_131]
        at uk.tim740.skUtilities.skUtilities.updateChk(skUtilities.java:97) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [server.jar:git-Spigot-d21162c-61e0c69]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-d21162c-61e0c69]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-d21162c-61e0c69]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-d21162c-61e0c69]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-d21162c-61e0c69]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-d21162c-61e0c69]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
`

**Comment by games647** [comment]
Please read the message again. It just warns you about a performance issue that can be fixed easily if you contact the developer of skUtilities.

>Plugin skUtilities is performing a blocking action on the main thread. This could be a performance hit Socket: https://raw.githubusercontent.com/tim740/skUtilities/master/latest.ver. Such actions should be handled async from the main thread. Report it to the plugin author [15:03:36 WARN]: [LagMonitor] The following exception is not an error. It's a hint for the plugin developer to find the source of the threading action. LagMonitor doesn't prevent this action. It just warns you
