### ISSUE TITLE
Pasting error

### ISSUE THREAD

**Issue by tobimori** [games647/LagMonitor#35]
`[14:56:03 ERROR]: [LagMonitor] null
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_131]
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[?:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023) ~[?:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125) ~[?:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[?:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) ~[?:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387) ~[?:1.8.0_131]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_131]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_131]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316) ~[?:1.8.0_131]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291) ~[?:1.8.0_131]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250) ~[?:1.8.0_131]
        at com.github.games647.lagmonitor.tasks.MonitorTask.paste(MonitorTask.java:93) ~[?:?]
        at com.github.games647.lagmonitor.commands.MonitorCommand.lambda$pasteMonitor$1(MonitorCommand.java:132) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [server.jar:git-Spigot-d21162c-61e0c69]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-d21162c-61e0c69]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
`

**Comment by games647** [comment]
Update your Java version. Your JVM doesn't support newer SSL certificates.

**Comment by tobimori** [comment]
It worked yesterday.

**Comment by games647** [comment]
Just try to update it.

**Comment by tobimori** [comment]
I used[ this guide](https://linoxide.com/debian/install-java-8-debian-gnulinux-9-stretch/) to install Java, how to update it?

**Comment by games647** [comment]
`sudo apt update && sudo apt upgrade`

**Comment by tobimori** [comment]
not working

**Comment by games647** [comment]
Which OS version do you use?

**Comment by tobimori** [comment]
https://prnt.sc/hcyyr4

**Comment by games647** [comment]
Change the target distro-id of the PPA from yakkety to zesty

**Comment by tobimori** [comment]
Okay it's now Java v1.8.0_151
I will try that later.
