### ISSUE TITLE
NoSuchMethodError .WinNT$PSID.createFieldsOrder(Ljava/lang/String;)Ljava/util/List;

### ISSUE THREAD

**Issue by mckite** [games647/LagMonitor#41]
[16:16:47 ERROR]: Error occurred while enabling LagMonitor v1.17 (Is it up to date?)
java.lang.NoSuchMethodError: com.sun.jna.platform.win32.WinNT$PSID.createFieldsOrder(Ljava/lang/String;)Ljava/util/List;
        at com.sun.jna.platform.win32.WinNT$PSID.<clinit>(WinNT.java:354) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_172]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_172]
        at com.sun.proxy.$Proxy43.<clinit>(Unknown Source) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_172]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_172]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_172]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_172]
        at java.lang.reflect.Proxy.newProxyInstance(Unknown Source) ~[?:1.8.0_172]
        at com.sun.jna.Native.loadLibrary(Native.java:506) ~[?:?]
        at com.sun.jna.platform.win32.Advapi32.<clinit>(Advapi32.java:67) ~[?:?]
        at lagmonitor.oshi.software.os.windows.WindowsOperatingSystem.enableDebugPrivilege(WindowsOperatingSystem.java:267) ~[?:?]
        at lagmonitor.oshi.software.os.windows.WindowsOperatingSystem.<clinit>(WindowsOperatingSystem.java:85) ~[?:?]
        at lagmonitor.oshi.SystemInfo.getOperatingSystem(SystemInfo.java:92) ~[?:?]
        at com.github.games647.lagmonitor.NativeData.<init>(NativeData.java:40) ~[?:?]
        at com.github.games647.lagmonitor.LagMonitor.setupNativeAdapter(LagMonitor.java:169) ~[?:?]
        at com.github.games647.lagmonitor.LagMonitor.onEnable(LagMonitor.java:86) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at com.massivecraft.massivelag.inject.MassiveLagPluginLoader.enablePlugin(MassiveLagPluginLoader.java:215) [MassiveLag.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
[16:16:47 INFO]: [Titlebar] Enabling Titlebar v1.3.2.7

**Comment by games647** [comment]
Could you please try a development build and provide your operation system version?

**Comment by mckite** [comment]
Where is the development build?
My OS version is Window 10 pro K 64bit ,
Java 8_172

**Comment by games647** [comment]
https://github.com/games647/LagMonitor#development-builds

**Comment by mckite** [comment]
Dev version, also can't load.
[17:04:11 ERROR]: Error occurred while enabling LagMonitor v1.17.1-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: com.sun.jna.platform.win32.WinNT$PSID.createFieldsOrder(Ljava/lang/String;)Ljava/util/List;
        at com.sun.jna.platform.win32.WinNT$PSID.<clinit>(WinNT.java:354) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_172]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_172]
        at com.sun.proxy.$Proxy43.<clinit>(Unknown Source) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_172]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_172]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_172]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_172]
        at java.lang.reflect.Proxy.newProxyInstance(Unknown Source) ~[?:1.8.0_172]
        at com.sun.jna.Native.loadLibrary(Native.java:506) ~[?:?]
        at com.sun.jna.platform.win32.Advapi32.<clinit>(Advapi32.java:67) ~[?:?]
        at lagmonitor.oshi.software.os.windows.WindowsOperatingSystem.enableDebugPrivilege(WindowsOperatingSystem.java:267) ~[?:?]
        at lagmonitor.oshi.software.os.windows.WindowsOperatingSystem.<clinit>(WindowsOperatingSystem.java:85) ~[?:?]
        at lagmonitor.oshi.SystemInfo.getOperatingSystem(SystemInfo.java:92) ~[?:?]
        at com.github.games647.lagmonitor.LagMonitor.setupNativeAdapter(LagMonitor.java:161) ~[?:?]
        at com.github.games647.lagmonitor.LagMonitor.onEnable(LagMonitor.java:86) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at com.massivecraft.massivelag.inject.MassiveLagPluginLoader.enablePlugin(MassiveLagPluginLoader.java:215) [MassiveLag.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
[17:04:11 INFO]: [Titlebar] Enabling Titlebar v1.3.2.7

When donwload the source and put in ecplise.
the error occures in line:          "  new SystemInfo().getOperatingSystem().getProcessId();"

The type lagmonitor.oshi.software.os.OperatingSystem cannot be resolved. It is indirectly referenced from required .class files


Other sources OK
        //test the library
        try {
            **new SystemInfo().getOperatingSystem().getProcessId();**
            nativeData = new NativeData(getLogger(), info);
        } catch (UnsatisfiedLinkError | NoClassDefFoundError linkError) {
            getLogger().log(Level.INFO, "Cannot load native library. Continuing without it...", linkError);
            nativeData = new NativeData(getLogger(), null);

**Comment by games647** [comment]
>The type lagmonitor.oshi.software.os.OperatingSystem cannot be resolved. It is indirectly referenced from required .class files

You forget that this project performs reshading (moving libraries to a different package). If you look inside the jar you can see that this path in fact exists. Otherwise the error would be different that the one you reported. Could post what other plugins do you use I guess there is another plugin that uses JNA besides LagMonitor.

**Comment by mckite** [comment]
The Dev version have same errors.

And the In ecplise.
The import API/Libaray is OK, but
Same error in "  new SystemInfo().getOperatingSystem().getProcessId();"

[23:22:22 ERROR]: Error occurred while enabling LagMonitor v1.17.1-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: com.sun.jna.platform.win32.WinNT$PSID.createFieldsOrder(Ljava/lang/String;)Ljava/util/List;
        at com.sun.jna.platform.win32.WinNT$PSID.<clinit>(WinNT.java:354) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_172]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_172]
        at com.sun.proxy.$Proxy43.<clinit>(Unknown Source) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_172]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_172]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_172]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_172]
        at java.lang.reflect.Proxy.newProxyInstance(Unknown Source) ~[?:1.8.0_172]
        at com.sun.jna.Native.loadLibrary(Native.java:506) ~[?:?]
        at com.sun.jna.platform.win32.Advapi32.<clinit>(Advapi32.java:67) ~[?:?]
        at lagmonitor.oshi.software.os.windows.WindowsOperatingSystem.enableDebugPrivilege(WindowsOperatingSystem.java:267) ~[?:?]
        at lagmonitor.oshi.software.os.windows.WindowsOperatingSystem.<clinit>(WindowsOperatingSystem.java:85) ~[?:?]
        at lagmonitor.oshi.SystemInfo.getOperatingSystem(SystemInfo.java:92) ~[?:?]
        at com.github.games647.lagmonitor.LagMonitor.setupNativeAdapter(LagMonitor.java:161) ~[?:?]
        at com.github.games647.lagmonitor.LagMonitor.onEnable(LagMonitor.java:86) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at com.massivecraft.massivelag.inject.MassiveLagPluginLoader.enablePlugin(MassiveLagPluginLoader.java:215) [MassiveLag.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]

**Comment by TrademarkTM** [comment]
I am having the same error.
```
[10:07:18] [Server thread/INFO]: [LagMonitor] Enabling LagMonitor v1.17.1-SNAPSHOT
[10:07:18] [Server thread/INFO]: [LagMonitor] Found JNA native library. Enabling extended native data support to display more data
[10:07:18] [Server thread/INFO]: Trying (via loadLibrary) jnidispatch
[10:07:18] [Server thread/INFO]: Looking in classpath from org.bukkit.plugin.java.PluginClassLoader@10dc3107 for /com/sun/jna/win32-x86-64/jnidispatch.dll
[10:07:18] [Server thread/INFO]: Found library resource at jar:file:/D:/Arquivos/Área%20de%20Trabalho/Survival/plugins/AuthMe%205.4.0.jar!/com/sun/jna/win32-x86-64/jnidispatch.dll
[10:07:18] [Server thread/INFO]: Trying C:\Users\EWS\AppData\Local\Temp\jna-69089\jna3887567255615635928.dll
[10:07:18] [Server thread/INFO]: Found jnidispatch at C:\Users\EWS\AppData\Local\Temp\jna-69089\jna3887567255615635928.dll
[10:07:18] [Server thread/INFO]: Looking for library 'Advapi32'
[10:07:18] [Server thread/INFO]: Adding paths from jna.library.path: null
[10:07:18] [Server thread/INFO]: Trying Advapi32.dll
[10:07:18] [Server thread/INFO]: Found library 'Advapi32' at Advapi32.dll
[10:07:18] [Server thread/ERROR]: Error occurred while enabling LagMonitor v1.17.1-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: com.sun.jna.platform.win32.WinNT$PSID.createFieldsOrder(Ljava/lang/String;)Ljava/util/List;
	at com.sun.jna.platform.win32.WinNT$PSID.<clinit>(WinNT.java:354) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_131]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_131]
	at com.sun.proxy.$Proxy66.<clinit>(Unknown Source) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Proxy.newProxyInstance(Unknown Source) ~[?:1.8.0_131]
	at com.sun.jna.Native.loadLibrary(Native.java:506) ~[?:?]
	at com.sun.jna.platform.win32.Advapi32.<clinit>(Advapi32.java:67) ~[?:?]
	at lagmonitor.oshi.software.os.windows.WindowsOperatingSystem.enableDebugPrivilege(WindowsOperatingSystem.java:267) ~[?:?]
	at lagmonitor.oshi.software.os.windows.WindowsOperatingSystem.<clinit>(WindowsOperatingSystem.java:85) ~[?:?]
	at lagmonitor.oshi.SystemInfo.getOperatingSystem(SystemInfo.java:92) ~[?:?]
	at com.github.games647.lagmonitor.LagMonitor.setupNativeAdapter(LagMonitor.java:161) ~[?:?]
	at com.github.games647.lagmonitor.LagMonitor.onEnable(LagMonitor.java:86) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```
I'm currently using:
- Spigot 1.12.2
- The lastest dev build of LagMonitor (145)
- Java 8
- Windows 10

**Comment by games647** [comment]
@TrademarkTM Thanks that helps a lot. AuthMe causes the issue here. They ship a different version of JNA and therefore causes incompatibility issues. Unfortunately you can only use one JNA per Java process. So we have to disable the native library then.
