### ISSUE TITLE
java.lang.NoClassDefFoundError: com/sun/jna/win32/StdCallLibrary

### ISSUE THREAD

**Issue by cjbrick910** [games647/LagMonitor#42]
[Server thread/ERROR]: Error occurred while enabling LagMonitor v1.17 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sun/jna/win32/StdCallLibrary
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_171]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_171]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:148) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at lagmonitor.oshi.software.os.windows.WindowsOperatingSystem.enableDebugPrivilege(WindowsOperatingSystem.java:267) ~[?:?]
	at lagmonitor.oshi.software.os.windows.WindowsOperatingSystem.<clinit>(WindowsOperatingSystem.java:85) ~[?:?]
	at lagmonitor.oshi.SystemInfo.getOperatingSystem(SystemInfo.java:92) ~[?:?]
	at com.github.games647.lagmonitor.NativeData.<init>(NativeData.java:40) ~[?:?]
	at com.github.games647.lagmonitor.LagMonitor.setupNativeAdapter(LagMonitor.java:169) ~[?:?]
	at com.github.games647.lagmonitor.LagMonitor.onEnable(LagMonitor.java:86) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:752) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.Bukkit.reload(Bukkit.java:525) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: com.sun.jna.win32.StdCallLibrary
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	... 31 more

my system:
Windows Server 2012 R2 64Bit
Java 1.8.0_171
Spigot 1.12.2
JNA 4.4.0
I'm using a non-development build, but I will try it now
Hopefully, you can help me fix this error
Thanks!

**Comment by games647** [comment]
Was it successful with a development build?
