### ISSUE TITLE
Mysql Problem #2

### ISSUE THREAD

**Issue by GABRYCA** [games647/LagMonitor#48]
Guys, i have this error and i don't know how to fix this
<code>
19.01 15:50:43 [Server] ERROR [LagMonitor] Error saving native stats to database
19.01 15:50:43 [Server] INFO com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'net_write' at row 1
19.01 15:50:43 [Server] INFO at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971) ~[server.jar:git-Spigot-596221b-9a1fc1e]
19.01 15:50:43 [Server] INFO at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[server.jar:git-Spigot-596221b-9a1fc1e]
19.01 15:50:43 [Server] INFO at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[server.jar:git-Spigot-596221b-9a1fc1e]
19.01 15:50:43 [Server] INFO at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[server.jar:git-Spigot-596221b-9a1fc1e]
19.01 15:50:43 [Server] INFO at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2490) ~[server.jar:git-Spigot-596221b-9a1fc1e]
19.01 15:50:43 [Server] INFO at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[server.jar:git-Spigot-596221b-9a1fc1e]
19.01 15:50:43 [Server] INFO at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197) ~[server.jar:git-Spigot-596221b-9a1fc1e]
19.01 15:50:43 [Server] INFO at com.github.games647.lagmonitor.storage.Storage.saveNative(Storage.java:181) [LagMonitor.jar:?]
19.01 15:50:43 [Server] INFO at com.github.games647.lagmonitor.storage.NativeSaveTask.run(NativeSaveTask.java:100) [LagMonitor.jar:?]
19.01 15:50:43 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [server.jar:git-Spigot-596221b-9a1fc1e]
19.01 15:50:43 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-596221b-9a1fc1e]
19.01 15:50:43 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
19.01 15:50:43 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
19.01 15:50:43 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
19.01 15:50:43 [Server] ERROR [LagMonitor] Using this data [0, 0, 293391, 68.25, 0, 0, 130095, 1276236]
</code>

It's about MySql, by default that columns it's INT(11), i tryed VARCHAR(10) but nothing, i still have that error

**Comment by GABRYCA** [comment]
I downloaded a dev build and this fixed
