### ISSUE TITLE
NoClassDefFoundError: net/md_5/bungee/api/ChatColor

### ISSUE THREAD

**Issue by Inysal** [games647/LagMonitor#7]
[Server thread/ERROR]: Error occurred while enabling LagMonitor v1.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
	at com.github.games647.lagmonitor.commands.StackTraceCommand.<clinit>(StackTraceCommand.java:23) ~[?:?]
	at com.github.games647.lagmonitor.LagMonitor.registerCommands(LagMonitor.java:154) ~[?:?]
	at com.github.games647.lagmonitor.LagMonitor.onEnable(LagMonitor.java:59) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit-1.9.2-R0.1.jar:git-Bukkit-935f18b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit-1.9.2-R0.1.jar:git-Bukkit-935f18b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.9.2-R0.1.jar:git-Bukkit-935f18b]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:346) [craftbukkit-1.9.2-R0.1.jar:git-Bukkit-935f18b]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:318) [craftbukkit-1.9.2-R0.1.jar:git-Bukkit-935f18b]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:403) [craftbukkit-1.9.2-R0.1.jar:git-Bukkit-935f18b]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:368) [craftbukkit-1.9.2-R0.1.jar:git-Bukkit-935f18b]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:323) [craftbukkit-1.9.2-R0.1.jar:git-Bukkit-935f18b]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:241) [craftbukkit-1.9.2-R0.1.jar:git-Bukkit-935f18b]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit-1.9.2-R0.1.jar:git-Bukkit-935f18b]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.ChatColor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.9.2-R0.1.jar:git-Bukkit-935f18b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.9.2-R0.1.jar:git-Bukkit-935f18b]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_60]
	... 14 more
[21:56:24]

**Comment by sgdc3** [comment]
You need to use Spigot, not craftbukkit ;)

**Comment by games647** [comment]
@Inysal Why do you still use CraftBukkit? Spigot is nearly the same. Only with some optimizations.

**Comment by sgdc3** [comment]
@games647 yeah but you should stop using md5's chatcolor xD

**Comment by games647** [comment]
It's not only the chatcolor. I use the API for clickable chat components. Since it's included in all 1.8+ Spigot builds, I don't think it's problem to use it.

**Comment by Inysal** [comment]
Sorry for the late reply. I don't know what I was thinking. Using Spigot v1.9.2 No issue to report. ^^

**Comment by games647** [comment]
Good to know. Thanks
