### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by SlimeDog** [games647/LagMonitor#92]
Spigot 1.16.4
LagMonitor 1.17.1-b172

On server start-up
```
[16:40:32] [Server thread/ERROR]: Could not load 'plugins/LagMonitor-1.17.1-b172.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:383) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:808) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ExceptionInInitializerError
        at com.github.games647.lagmonitor.LagMonitor.<init>(LagMonitor.java:58) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        ... 7 more
Caused by: java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(CraftPlayer)EntityPlayer to ()Player
        at java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:861) ~[?:?]
        at java.lang.invoke.MethodHandle.asType(MethodHandle.java:847) ~[?:?]
        at com.github.games647.lagmonitor.task.PingManager.<clinit>(PingManager.java:49) ~[?:?]
        at com.github.games647.lagmonitor.LagMonitor.<init>(LagMonitor.java:58) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        ... 7 more
```

UPDATE:
This error occurs starting with LagMonitor-1.17.1-b166, and is found in every subsequent dev build through b175. I stopped testing at that point, so I do not know about subsequent builds (b177 is current, as of this update).

This error also occurs on Spigot 1.16.5. It does not occur on Paper 1.16.4 or 1.16.5, with the same (large) set of plugins.

**Comment by SlimeDog** [comment]
FWIW, this error does not occur on Paper 1.16.4 with the same (large) set of plugins.

**Comment by SlimeDog** [comment]
This error occurs starting with LagMonitor-1.17.1-b166, and is found in every subsequent dev build through b174.

This error also occurs on Spigot 1.16.5. It does not occur on Paper 1.16.4 or 1.16.5, with the same (large) set of plugins.

**Comment by SlimeDog** [comment]
This error persists on Spigot with LagMonitor-1.17.1-b175.

**Comment by games647** [comment]
Now the plugin should no longer fail if this component errors out.

**Comment by SlimeDog** [comment]
Sounds good. I non longer use this plugin, so I cannot confirm.
